DROP SCHEMA IF EXISTS otus3;
CREATE SCHEMA otus3;
USE otus3;
DROP TABLE IF EXISTS USERS2;
CREATE TABLE USERS2
(
  id   BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  age  INT(3)     NOT NULL
);